import mongoose, { Schema, Document, Model, Types } from "mongoose";
import { EMAIL_REGEX, PASSWORD_REGEX } from "../../utils/regex";

export type UserRole = "Admin" | "User";

/**
 * DONE:
 * Define User interface
 * _id, email, password, role, authToken?
 */
export interface IUser extends Document {
  _id: Types.ObjectId;
  email: string;
  password: string;
  role: UserRole;
  authToken?: string;
}

/**
 * DONE:
 * Design User Schema
 * 1. _id: auto generated by mongoose
 * 2. email: should satisfy the format
 * 3. password: no length limit for now
 * 4. authToken: will be generated after user FIRST login
 */
const UserSchema: Schema<IUser> = new Schema({
  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    match: EMAIL_REGEX,
  },
  password: {
    type: String,
    required: true,
    match: PASSWORD_REGEX,
  },
  role: {
    type: String,
    enum: ["Admin", "User"],
    required: true,
  },
  authToken: {
    type: String,
    default: null,
  },
});

// Export the model
const User: Model<IUser> = mongoose.model<IUser>("User", UserSchema);
export default User;
